[tools]
deno = "latest"
node = "latest"
lua = "latest"
python = "latest"
github-cli = "latest"
ghq = "latest"
usage = "latest"
gotestsum = "latest"
gemini = "latest"
claude = "latest"
pre-commit = "latest"
lefthook = "latest"

[settings]
idiomatic_version_file_enable_tools = ["python"]
