core:
  restore:
    verbose: true
    confirm: true
ui:
  density: spacious
  style:
    # Change color with Catpuccin Frappe palette(https://github.com/catppuccin/catppuccin#-palette)
    list_view:
      indent_on_select: true
      cursor: "#ca9ee6" # Mauve
      selected: "#a6d189" # Green
    detail_view:
      border: "#85c1dc" # Sapphire
      info_pane:
        deleted_from:
          fg: "#c6d0f5" # Text
          bg: "#303446" # Base
        deleted_at:
          fg: "#a5adce" # Subtext0
          bg: "#303446" # Base
      preview_pane:
        border: "#85c1dc" # Sapphire
        size:
          fg: "#81c8be" # Teal
          bg: "#303446" # Base
        scroll:
          fg: "#81c8be" # Teal
          bg: "#292c3c" # Mantle
  exit_message: bye!
  preview:
    syntax_highlight: true
    colorscheme: catppuccin-frappe
    directory_command: ls -GF -1 -A --color=always
  paginator_type: dots
history:
  include:
    within_days: 365
  exclude:
    files:
      - .DS_Store
    patterns: []
    globs: []
    size:
      min: 0KB
      max: 10GB
