format = """
$os\
$username\
$hostname\
$directory\
$git_branch\
$git_state\
$git_status\
$docker_context\
$golang\
$lua\
$nodejs\
$python\
$rust\
$line_break\
$character"""

[username]
format = "[$user]($style)"

[hostname]
format = "[ ($ssh_symbol$hostname)]($style)"
ssh_symbol = " "

[directory]
style = "blue"
read_only = " 󰌾"

[character]
success_symbol = "[❯](purple)"
error_symbol = "[❯](red)"
vimcmd_symbol = "[❮](green)"

[git_branch]
symbol = ""
format = "[$symbol$branch]($style)"
style = "bright-yellow"

[git_status]
format = "[[(*$conflicted$untracked$modified$staged$renamed$deleted)](218) ($ahead_behind$stashed)]($style)"
style = "cyan"
conflicted = "​"
untracked = "​"
modified = "​"
staged = "​"
renamed = "​"
deleted = "​"
stashed = "≡"

[git_state]
format = '\([$state( $progress_current/$progress_total)]($style)\) '
style = "bright-black"

[cmd_duration]
disabled = true
format = "[$duration]($style) "
style = "yellow"

[package]
disabled = true

# Nerd Font Icons
# https://starship.rs/presets/nerd-font
[docker_context]
format = "[$symbol$context]($style) "
symbol = " "

[golang]
format = "[$symbol($version )]($style)"
symbol = " "

[lua]
format = "[$symbol($version )]($style)"
symbol = " "

[nodejs]
format = "[$symbol($version )]($style)"
symbol = " "

[python]
format = "[${symbol}${pyenv_prefix}(${version} )(\\($virtualenv\\) )]($style)"
symbol = " "

[rust]
format = "[${symbol}${version} ]($style)"
symbol = ""

[os]
disabled = false

[os.symbols]
Alpaquita = " "
Alpine = " "
AlmaLinux = " "
Amazon = " "
Android = " "
Arch = "[ ](fg:blue)"
Artix = " "
CentOS = " "
Debian = " "
DragonFly = " "
Emscripten = " "
EndeavourOS = " "
Fedora = " "
FreeBSD = " "
Garuda = "󰛓 "
Gentoo = " "
HardenedBSD = "󰞌 "
Illumos = "󰈸 "
Kali = " " 
Linux = " "
Mabox = " "
Macos = " (fg:#c7c8ca)"
Manjaro = "[ ](fg:green)"
Mariner = " "
MidnightBSD = " "
Mint = " "
NetBSD = " "
NixOS = " "
OpenBSD = "󰈺 "
openSUSE = " "
OracleLinux = "󰌷 "
Pop = " "
Raspbian = " "
Redhat = " "
RedHatEnterprise = " "
RockyLinux = " "
Redox = "󰀘 "
Solus = "󰠳 "
SUSE = " "
Ubuntu = "[ ](fg:#E95420)"
Unknown = " "
Void = " "
Windows = "󰍲 "
