name: arch

on:
  push:
    branches: [main]
  # pull_request:
  #   branches: [main]

jobs:
  arch-test:
    runs-on: ubuntu-latest
    # if: ${{ contains(github.event.head_commit.message, "[CI]") }}
    container:
      image: archlinux:latest

    steps:
      - uses: actions/checkout@v3

      - name: Update pacman
        run: pacman -Syu --noconfirm

      # - name: Install sudo
      #   run: pacman -Sy --noconfirm sudo
      #
      # - name: Create test user
      #   run: |
      #     useradd -m -g wheel -s /bin/bash test
      #     echo test:test | chpasswd
      #     sed -i -e "s/# %wheel ALL=(ALL:ALL) NOPASSWD: ALL/%wheel ALL=(ALL:ALL) NOPASSWD: ALL/" /etc/sudoers
      #
      # - name: Login test user
      #   run: su - test

      - name: Install sudo
        run: pacman -Sy --noconfirm sudo

      # - name: ADD SSH KEY
      #   env:
      #     SSH_KEY: ${{ secrets.ACTION_SSH }}
      #   run: |
      #     mkdir -p ~/.ssh
      #     echo "$ssh_key" | tr -d '\r' > ~/.ssh/id_ed25519
      #     chmod 700 ~/.ssh/id_ed25519
      #     eval $(ssh-agent -s)
      #     ssh-add ~/.ssh/id_ed25519
      #     ssh-keyscan -H -t ed25519 github.com >> ~/.ssh/known_hosts
      #     cat ~/.ssh/known_hosts

      # - name: Check chezmoi
      #   run: |
      #     pacman -Sy --noconfirm chezmoi
      #     chezmoi init git@github.com:radiol/dotfiles.git

      # # Error Check
      - name: Run install.sh
        run: |
          # sed -i -e "s/sudo //" install_arch.sh
          /bin/bash ${GITHUB_WORKSPACE}/install_arch.sh

      # - name: Copy dotfiles
      #   run: |
      #     mkdir -p ~/.local/share/
      #     cp -r ${GITHUB_WORKSPACE}/* ~/.local/share/chezmoi
      #     ls ~/.local/share/chezmoi

      - name: Run chezmoi
        run: chezmoi apply -S ${GITHUB_WORKSPACE}

      - name: Load zsh
        run: |
          zsh -i -l -c exit
          zsh -i -l -c exit 2> error.log; cat error.log
          cat error.log
          # if [ -s error.log ]; then false; fi

      - name: Check lazy.nvim dir
        run: ls ~/.local/share/
