name: arch

on:
  push:
    branches: [main]
  # pull_request:
  #   branches: [main]

jobs:
  arch-test:
    runs-on: ubuntu-latest
    # if: ${{ contains(github.event.head_commit.message, "[CI]") }}
    container:
      image: archlinux:latest

    steps:
      - uses: actions/checkout@v3

      - name: Update pacman
        run: pacman -Syu --noconfirm

      - name: Install sudo
        run: pacman -Sy --noconfirm sudo git curl

      - name: Run chezmoi
        run: sh -c "$(curl -fsLS chezmoi.io/get)" -- init --apply radiol

      - name: Run once script
        run: /bin/bash ~/.local/share/chezmoi/run_once_install.sh

      # # Error Check
      - name: Load zsh
        run: |
          zsh -i -l -c exit
          zsh -i -l -c exit 2> error.log; cat error.log
          cat error.log
          if [ -s error.log ]; then false; fi

      - name: Check lazy.nvim dir
        run: |
          ls ~/.local/share/nvim/lazy/
