name: macos

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  macos-test:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v3

      # Error Check
      - name: Run install.sh
        run: /bin/bash ${GITHUB_WORKSPACE}/init.sh

      - name: Load .zshenv
        run: |
          zsh ~/.config/zsh/.zshrc 2> error.log; cat error.log
          if [ -s error.log ]; then false; fi